import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import branchesRouter from "./branches";
import roomsRouter from "./rooms";
import productsRouter from "./products";
import reservationsRouter from "./reservations";
import ordersRouter from "./orders";
import receiptsRouter from "./receipts";
import staffAvailabilityRouter from "./staff-availability";
import staffRouter from "./staff";
import schedulesRouter from "./schedules";
import agentsRouter from "./agents";
import shareholdersRouter from "./shareholders";
import investorRouter from "./investor";
import reportsRouter from "./reports";
import currencyRouter from "./currency";
import customerAuthRouter from "./customer-auth";
import customerBookingsRouter from "./customer-bookings";
import webhooksRouter from "./webhooks";
import attendanceApiRouter from "./attendance-api";
import availabilityRouter from "./availability";
import folioRouter from "./folio";
import paymentsApiRouter from "./payments-api";
import tablesApiRouter from "./tables-api";
import managerRouter from "./manager";
import hostessPortalRouter from "./hostess-portal";
import driverRouter from "./driver";
import hostessProfilesRouter from "./hostess-profiles";
import agencyMgmtRouter from "./agency-mgmt";
import roomTablesRouter from "./room-tables";
import settingsMenuConfigRouter from "./settings-menu-config";
import menuRouter from "./menu";
import hostessAssignmentsRouter from "./hostessAssignments";
import agencyReconciliationRouter from "./agencyReconciliation";
import ledgerRouter from "./ledger";
import adminUsersRouter from "./admin/users";
import dashboardsRouter from "./dashboards";
import profileRouter from "./profile";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(branchesRouter);
router.use(roomsRouter);
router.use(productsRouter);
router.use(reservationsRouter);
router.use(ordersRouter);
router.use(receiptsRouter);
router.use(staffAvailabilityRouter);
router.use(staffRouter);
router.use(schedulesRouter);
router.use(agentsRouter);
router.use(shareholdersRouter);
router.use(investorRouter);
router.use(reportsRouter);
router.use(currencyRouter);
router.use(customerAuthRouter);
router.use(customerBookingsRouter);
router.use(webhooksRouter);
router.use(attendanceApiRouter);
router.use(availabilityRouter);
router.use(folioRouter);
router.use(paymentsApiRouter);
router.use(tablesApiRouter);
router.use(managerRouter);
router.use(hostessPortalRouter);
router.use(driverRouter);
router.use(hostessProfilesRouter);
router.use(agencyMgmtRouter);
router.use(roomTablesRouter);
router.use(settingsMenuConfigRouter);
router.use(menuRouter);
router.use(hostessAssignmentsRouter);
router.use(agencyReconciliationRouter);
router.use(ledgerRouter);
router.use(adminUsersRouter);
router.use(dashboardsRouter);
router.use(profileRouter);

export default router;
